project:
  type: website
  output-dir: docs
  
website:
  title: "Justine Shakespeare's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      
# (this is where you put the different links on the nav bar)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

    mainfont: "Arial"
    fontsize: 1.25rem
    linkcolor: "#E84855"

# (For more options: https://quarto.org/docs/output-formats/html-themes.html)

editor: visual

